---
title: About Me
author: Katie Hosey
date: '2018-06-18'
slug: about-me
categories: []
tags: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# About Me 

Helloooo. My name is Katie Hosey and I’m from Wilmington, Delaware. I’ve got 2 amazing parents and 2 older brothers, who I’ve always been grateful for. (Boys are fairly simple creatures, but they can be a bit overwhelming if you didn’t grow up with one or two.) I’m currently a third year at the University of Virginia, majoring in Cognitive Science with a concentration in Neuroscience and minoring in History and Psychology. I absolutely love school and learning; I’ve never taken a class and not found the information I’ve learned interesting or valuable in some way. I’m very excited to be currently studying in Cape Town, and though I find Data Science to be interesting, it’s a bit overwhelming right now. I’m excited for the internship portion of the class to see how all of this information is applied in the workplace. I’m still undecided on studying abroad again in the spring of my third year, but if I don’t live abroad again in my undergrad, I hope to be able to in my postgrad years. After college, I have no idea what my plans are specifically. I’ve thought about doing Teach for America for 2 years before doing grad school in some subject that I’ve yet to decide on. I change my mind about my future just about everyday, which stresses me out just about every other day (to go in theme with my ever-changing mentality). Currently, I’m hoping that I can make more of an effort to reach the goals I set for myself throughout the next school year, especially those regarding attaining more consistency in my life. I guess we’ll see how I feel about that tomorrow. 
